---
- name: Copy Kubeconfig
  block:
    - name: Make sure ~/.kube directory exists
      file:
        path: "~/.kube"
        state: directory

    - name: Copy kubeconfig file to a ~/.kube dirctory
      copy:
        src: "{{ config_dir }}/admin.conf"
        dest: "~/.kube/config"
        mode: "0600"
  when:
    - config.kubernetes.other.copyKubeconfig is defined
    - config.kubernetes.other.copyKubeconfig == true