- name: Clone Kubespray and generate required configs
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: config/cluster/import
    - role: config/infra/import
    - role: generate/inventory/nodes
    - role: kubespray
