---
- name: Ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "{{ config_dir }}/group_vars/all"
    - "{{ config_dir }}/group_vars/k8s_cluster"

- name: Generate Kubespray all.yaml
  template:
    src: "{{ templates_dir }}/kubespray/all.yaml.j2"
    dest: "{{ config_dir }}/group_vars/all/all.yaml"
    # Preserve Kubespray variables intact
    variable_start_string: "<<"
    variable_end_string: ">>"

- name: Generate Kubespray k8s_cluster.yaml
  template:
    src: "{{ templates_dir }}/kubespray/k8s_cluster.yaml.j2"
    dest: "{{ config_dir }}/group_vars/k8s_cluster/k8s_cluster.yaml"
    # Preserve Kubespray variables intact
    variable_start_string: "<<"
    variable_end_string: ">>"
    block_start_string: "<%"
    block_end_string: "%>"

- name: Generate Kubespray etcd.yaml
  template:
    src: "{{ templates_dir }}/kubespray/etcd.yaml.j2"
    dest: "{{ config_dir }}/group_vars/etcd.yaml"
    #dest: {{ config_dir }}/group_vars/all/etcd.yaml

- name: Generate cluster's nodes.yaml
  template:
    src: "{{ templates_dir }}/kubespray/nodes.yaml.j2"
    dest: "{{ config_dir }}/nodes.yaml"
    lstrip_blocks: true