---
- name: Generate hosts.yaml file containing Kubitect hosts
  template:
    src: "{{ templates_dir }}/hosts.yaml.j2"
    dest: "{{ config_dir }}/hosts.yaml"
    mode: 0600
    lstrip_blocks: true

- name: Create main.tf from template file
  template:
    src: "{{ templates_dir }}/terraform/main.tf.j2"
    dest: ../../terraform/main.tf
  vars:
    host_list: "{{ config.hosts }}"

- name: Ensure SSH directory exists
  file:
    path: "{{ config_dir }}/.ssh"
    state: directory
    mode: 0700

- name: Check if private SSH key exists
  stat:
    path: "{{ config_dir }}/.ssh/id_rsa"
  register: ssh_key

- name: Check if public SSH key exists
  stat:
    path: "{{ config_dir }}/.ssh/id_rsa.pub"
  register: ssh_pub_key

- name: Generate SSH keys
  #ignore_errors: true
  openssh_keypair:
    path: "{{ config_dir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    mode: 0600 
    force: yes
  when:
    - not ssh_key.stat.exists or not ssh_pub_key.stat.exists